"use client";
import { FormEvent, useEffect, useState } from "react";

type User={id:string;email:string}; type Item={id:string;provider?:string;name?:string;kind?:string;label?:string}; type Msg={role:"user"|"assistant";content:string;trace?:unknown[]};
async function api(url:string,init?:RequestInit){const r=await fetch(url,init);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d}

function Login({done}:{done:(u:User)=>void}){const[signup,setSignup]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[err,setErr]=useState("");async function submit(e:FormEvent){e.preventDefault();try{const d=await api("/api/auth/"+(signup?"signup":"login"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});done(d.user)}catch(e){setErr(e instanceof Error?e.message:"Failed")}}return <main className="login"><form className="loginCard" onSubmit={submit}><div className="mark">O</div><small>SELF-HOSTED AGENT OS</small><h1>Own the tools.<br/>Own the agent.</h1><p>No Composio API or integration aggregator.</p><input placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={signup?10:1} required/>{err&&<div className="error">{err}</div>}<button className="primary">{signup?"Create account":"Sign in"}</button><button type="button" className="ghost" onClick={()=>setSignup(!signup)}>{signup?"Already registered? Sign in":"Create an account"}</button></form></main>}

export default function Home(){const[user,setUser]=useState<User|null|undefined>();const[tab,setTab]=useState("chat"),[connections,setConnections]=useState<Item[]>([]),[connectors,setConnectors]=useState<Item[]>([]),[messages,setMessages]=useState<Msg[]>([]),[input,setInput]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false);const[ai,setAi]=useState({baseURL:"",apiKey:"",model:""});const[form,setForm]=useState({name:"",kind:"openapi",url:"",token:""});
useEffect(()=>{api("/api/auth/me").then(d=>setUser(d.user)).catch(()=>setUser(null));const s=localStorage.getItem("omni_ai");if(s)try{setAi(a=>({...a,...JSON.parse(s),apiKey:""}))}catch{}},[]);function load(){if(!user)return;Promise.all([api("/api/connections"),api("/api/connectors")]).then(([a,b])=>{setConnections(a.connections||[]);setConnectors(b.connectors||[])})}useEffect(load,[user]);if(user===undefined)return <main className="center">Loading…</main>;if(!user)return <Login done={setUser}/>;
async function send(){const q=input.trim();if(!q||busy)return;const next=[...messages,{role:"user" as const,content:q}];setMessages(next);setInput("");setBusy(true);setErr("");try{const d=await api("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:next.map(x=>({role:x.role,content:x.content})),aiConfig:ai})});setMessages([...next,{role:"assistant",content:d.content||"",trace:d.trace||[]}])}catch(e){setErr(e instanceof Error?e.message:"Failed")}finally{setBusy(false)}}
async function addConnector(e:FormEvent){e.preventDefault();const config=form.kind==="mcp"?{url:form.url,headers:form.token?{Authorization:"Bearer "+form.token}:{}}:{specUrl:form.url,auth:form.token?{type:"bearer",token:form.token}:undefined};try{await api("/api/connectors",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.name,kind:form.kind,config})});setForm({name:"",kind:"openapi",url:"",token:""});load()}catch(e){setErr(e instanceof Error?e.message:"Failed")}}
const connected=new Set(connections.map(x=>x.provider));const oauth=[{id:"google",name:"Google Workspace",d:"Gmail · Drive · Calendar"},{id:"github",name:"GitHub",d:"Repos · issues · workflows"},{id:"slack",name:"Slack",d:"Channels · messages · files"}];
return <main className="shell"><aside><div className="brand"><div className="mark">O</div><b>OMNI</b></div><nav>{["chat","connections","connectors","settings"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav><div className="status"><i/>Independent runtime<br/><span>No Composio backend</span></div><button className="ghost" onClick={async()=>{await api("/api/auth/logout",{method:"POST"});setUser(null)}}>Sign out</button></aside><section className="work"><header><div><small>OMNI PLATFORM</small><h2>{tab[0].toUpperCase()+tab.slice(1)}</h2></div><strong>SELF-HOSTED</strong></header>
{tab==="chat"&&<div className="chat"><div className="feed">{messages.length===0&&<div className="hero"><div className="orb">∞</div><h1>One agent.<br/>Your infrastructure.</h1><p>Dynamic tool discovery across native OAuth apps, OpenAPI services and MCP servers.</p></div>}{messages.map((m,i)=><article className={m.role} key={i}><b>{m.role==="user"?"YOU":"OMNI"}</b><p>{m.content}</p>{m.trace?.length?<details><summary>{m.trace.length} tool steps</summary><pre>{JSON.stringify(m.trace,null,2)}</pre></details>:null}</article>)}{busy&&<article><p>Searching tools and executing…</p></article>}{err&&<div className="error">{err}</div>}</div><div className="composer"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask Omni to work across your apps…"/><button className="primary" onClick={send}>Send</button></div></div>}
{tab==="connections"&&<div className="grid"><div className="panel wide"><small>NATIVE OAUTH</small><h3>Connect apps</h3><div className="apps">{oauth.map(x=><div className="app" key={x.id}><div className="appmark">{x.name[0]}</div><div><b>{x.name}</b><span>{x.d}</span></div>{connected.has(x.id)?<em>Connected</em>:<a href={"/api/oauth/"+x.id+"/start"}>Connect</a>}</div>)}</div></div><div className="panel wide"><small>VAULT</small><h3>Connected accounts</h3>{connections.length?connections.map(x=><div className="row" key={x.id}><div><b>{x.provider}</b><span>{x.label}</span></div><button onClick={async()=>{await api("/api/connections",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:x.id})});load()}}>Disconnect</button></div>):<p className="muted">No connections yet.</p>}</div></div>}
{tab==="connectors"&&<div className="grid"><form className="panel" onSubmit={addConnector}><small>REGISTER</small><h3>OpenAPI / MCP</h3><input placeholder="Connector name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="openapi">OpenAPI</option><option value="mcp">Remote MCP</option></select><input placeholder="https:// endpoint or spec.json" value={form.url} onChange={e=>setForm({...form,url:e.target.value})} required/><input type="password" placeholder="Bearer token (optional)" value={form.token} onChange={e=>setForm({...form,token:e.target.value})}/><button className="primary">Add connector</button></form><div className="panel"><small>REGISTRY</small><h3>Custom connectors</h3>{connectors.length?connectors.map(x=><div className="row" key={x.id}><div><b>{x.name}</b><span>{x.kind}</span></div><button onClick={async()=>{await api("/api/connectors",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:x.id})});load()}}>Remove</button></div>):<p className="muted">Add any HTTPS OpenAPI JSON spec or Streamable HTTP MCP server.</p>}</div></div>}
{tab==="settings"&&<div className="grid"><div className="panel"><small>AI LAYER</small><h3>OpenAI-compatible endpoint</h3><input placeholder="Base URL" value={ai.baseURL} onChange={e=>setAi({...ai,baseURL:e.target.value})}/><input placeholder="Model" value={ai.model} onChange={e=>setAi({...ai,model:e.target.value})}/><input type="password" placeholder="API key" value={ai.apiKey} onChange={e=>setAi({...ai,apiKey:e.target.value})}/><button className="primary" onClick={()=>localStorage.setItem("omni_ai",JSON.stringify({baseURL:ai.baseURL,model:ai.model}))}>Save non-secret settings</button></div><div className="panel"><small>CORE</small><h3>Independent components</h3><ul><li>Own auth + sessions</li><li>AES-256-GCM token vault</li><li>OAuth refresh</li><li>Dynamic tool registry</li><li>OpenAPI importer</li><li>MCP client</li><li>Agent execution loop</li></ul></div></div>}</section></main>}